// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1hTSfopRvrnfcKsdweFOcrG3bUvXdwpI',
    appId: '1:298645858795:web:68f842bed5310cbd4e11ae',
    messagingSenderId: '298645858795',
    projectId: 'shipp-8ea12',
    authDomain: 'shipp-8ea12.firebaseapp.com',
    storageBucket: 'shipp-8ea12.firebasestorage.app',
    measurementId: 'G-KV2NNZ79E2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqKko9-8r2RMp_odLa6mIU7AHMbgpBAk0',
    appId: '1:298645858795:android:6f82c9eba83424704e11ae',
    messagingSenderId: '298645858795',
    projectId: 'shipp-8ea12',
    storageBucket: 'shipp-8ea12.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXMKIPDpQ6v-oibiYLOKrlYle2DrIADqA',
    appId: '1:298645858795:ios:95e0bae5aed168a74e11ae',
    messagingSenderId: '298645858795',
    projectId: 'shipp-8ea12',
    storageBucket: 'shipp-8ea12.firebasestorage.app',
    iosBundleId: 'com.example.shipp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXMKIPDpQ6v-oibiYLOKrlYle2DrIADqA',
    appId: '1:298645858795:ios:95e0bae5aed168a74e11ae',
    messagingSenderId: '298645858795',
    projectId: 'shipp-8ea12',
    storageBucket: 'shipp-8ea12.firebasestorage.app',
    iosBundleId: 'com.example.shipp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1hTSfopRvrnfcKsdweFOcrG3bUvXdwpI',
    appId: '1:298645858795:web:3c100a19c71f493c4e11ae',
    messagingSenderId: '298645858795',
    projectId: 'shipp-8ea12',
    authDomain: 'shipp-8ea12.firebaseapp.com',
    storageBucket: 'shipp-8ea12.firebasestorage.app',
    measurementId: 'G-X5G2PL5GXB',
  );
}
